name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Измените на название вашей основной ветки (main или master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Укажите используемую версию Node.js
          cache: 'npm' # Или 'yarn' в зависимости от вашего менеджера пакетов

      - name: Install dependencies
        run: npm install # Или yarn install

      - name: Build
        run: npm run build # Или yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Папка, которую нужно опубликовать 